version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=spongebob
      - POSTGRES_USER=usr_spongebob
      - POSTGRES_PASSWORD=12345
    ports:
      - '5432:5432'
    expose:
      - '5432'